version: "3"
services:
  app:
    extends:
      file: docker-compose.override.yml
      service: app
    image: sergeikiss/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
