version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  app:
    extends:
      file: docker-compose.override.yml
      service: app
    image: sergeikiss/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    env_file:
      - .env
    depends_on:
      - db
