version: "3"
services:
  app:
    extends:
      file: docker-compose.override.yml
      service: app
    build:
      context: .
      dockerfile: Dockerfile
    command: npm test
    volumes:
      - "./app:/app"